# Generated by Django 4.2.2 on 2026-01-09 01:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_coupon_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='news/photos/')),
                ('video', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='news/videos/')),
                ('is_carousel', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ('-creation_date',),
                'indexes': [models.Index(fields=['is_carousel'], name='administrat_is_caro_e8894f_idx'), models.Index(fields=['-creation_date'], name='administrat_creatio_642dd8_idx')],
            },
        ),
    ]
