# Generated by Django 4.2.2 on 2026-01-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
