# Generated by Django 4.2.2 on 2026-01-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_news_link'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='administrat_is_caro_e8894f_idx',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_carousel',
        ),
    ]
