# Generated by Django 4.2.2 on 2026-01-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_alter_accessory_console_alter_console_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('tasa 0', 'T0'), ('card', 'Card'), ('cash', 'Cash'), ('sinpe', 'Sinpe'), ('na', 'N/A')], default='na', max_length=100, null=True),
        ),
    ]
