# Generated by Django 4.2.2 on 2026-02-25 16:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='voucher',
            field=models.FileField(blank=True, help_text='Payment voucher (PDF or image) for online payments', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='sales/vouchers/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('tasa 0', 'T0'), ('card', 'Card'), ('cash', 'Cash'), ('sinpe', 'Sinpe'), ('transfer', 'Transfer'), ('na', 'N/A')], default='na', max_length=100, null=True),
        ),
    ]
