# Generated by Django 4.2.2 on 2026-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_sale_voucher_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='voucher',
            field=models.FileField(blank=True, help_text='Payment voucher (PDF or image) for online payments', null=True, upload_to='sales/vouchers/'),
        ),
    ]
